# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 07:43
from __future__ import unicode_literals

import common.field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', common.field.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=128)),
            ],
            options={
                'db_table': 'attribute_tab',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', common.field.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=64)),
                ('image', models.ImageField(max_length=255, null=True, upload_to=b'profile/')),
                ('total_point', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_tab',
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', common.field.BigAutoField(primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app_user.Attribute')),
                ('user', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app_user.User')),
            ],
            options={
                'db_table': 'user_attribute_tab',
            },
        ),
    ]
