# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='azure_person_id',
            field=models.CharField(default=b'', max_length=64),
        ),
    ]
