# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userluckydraw',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='userluckydraw',
            name='upd_time',
        ),
    ]
