# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20190726_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Init'), (2, b'Completed'), (3, b'Denied'), (4, b'Expired')], default=1),
        ),
    ]
